### ISSUE TITLE
Ubuntu 20.04 on root with "persistent datasets" created at install - `zfs-mount-generator` doesn't run on first boot?

### ISSUE THREAD

**Issue by albertmichaelj** [openzfs/openzfs-docs#34] opened 2020-07-12 15:39 UTC
I recently read [this](https://didrocks.fr/2020/06/16/zfs-focus-on-ubuntu-20.04-lts-zsys-dataset-layout/) article (and the related ones) `zsys`, and in the article they talk about the notion of "persistent datasets" for `zsys`. I was inspired to move my Ubuntu server installation to ZFS on root (single disk, no encryption) so that I could play around with `zsys`, and I wanted to replicate what they called the "server layout" i.e.:

```
$ zsysctl show --full
[…]
System Datasets:
 - bpool/BOOT/ubuntu_e2wti1
 - rpool/ROOT/ubuntu_e2wti1
 - rpool/ROOT/ubuntu_e2wti1/usr
 - rpool/ROOT/ubuntu_e2wti1/var
 - rpool/ROOT/ubuntu_e2wti1/var/lib/AccountsService
 - rpool/ROOT/ubuntu_e2wti1/var/lib/NetworkManager
 - rpool/ROOT/ubuntu_e2wti1/var/lib/apt
 - rpool/ROOT/ubuntu_e2wti1/var/lib/dpkg
User Datasets:
[…]
Persistent Datasets:
 - rpool/srv
 - rpool/usr/local
 - rpool/var/lib
 - rpool/var/games
 - rpool/var/log
 - rpool/var/mail
 - rpool/var/snap
 - rpool/var/spool
 - rpool/var/www
```

So, I decided to deviate a little from the instructions and create a layout as close to the above as I could. I ended up with the below datasets:
```
root@ubuntu:~# zfs list -o name,canmount,mountpoint,com.ubuntu.zsys:bootfs
NAME                                              CANMOUNT  MOUNTPOINT                    COM.UBUNTU.ZSYS:BOOTFS
bpool                                                  off  /mnt/boot                     -
bpool/BOOT                                             off  none                          -
bpool/BOOT/ubuntu_5235te                            noauto  /mnt/boot                     -
rpool                                                  off  /mnt                          -
rpool/ROOT                                             off  none                          -
rpool/ROOT/ubuntu_5235te                            noauto  /mnt                          yes
rpool/ROOT/ubuntu_5235te/srv                            on  /mnt/srv                      yes
rpool/ROOT/ubuntu_5235te/usr                            on  /mnt/usr                      no
rpool/ROOT/ubuntu_5235te/var                            on  /mnt/var                      no
rpool/ROOT/ubuntu_5235te/var/lib                       off  /mnt/var/lib                  no
rpool/ROOT/ubuntu_5235te/var/lib/AccountsService        on  /mnt/var/lib/AccountsService  no
rpool/ROOT/ubuntu_5235te/var/lib/NetworkManager         on  /mnt/var/lib/NetworkManager   no
rpool/ROOT/ubuntu_5235te/var/lib/apt                    on  /mnt/var/lib/apt              no
rpool/ROOT/ubuntu_5235te/var/lib/dpkg                   on  /mnt/var/lib/dpkg             no
rpool/USERDATA                                         off  /mnt                          -
rpool/USERDATA/root_5235te                              on  /mnt/root                     -
rpool/usr                                              off  /mnt/usr                      -
rpool/usr/local                                         on  /mnt/usr/local                -
rpool/var                                              off  /mnt/var                      -
rpool/var/games                                         on  /mnt/var/games                -
rpool/var/lib                                           on  /mnt/var/lib                  -
rpool/var/lib/docker                                    on  /mnt/var/lib/docker           -
rpool/var/log                                           on  /mnt/var/log                  -
rpool/var/mail                                          on  /mnt/var/mail                 -
rpool/var/snap                                          on  /mnt/var/snap                 -
rpool/var/spool                                         on  /mnt/var/spool                -
rpool/var/www                                           on  /mnt/var/www                  -
```

Based on my understanding of the `zfs-mount-generator` and `zsys`, the above configuration would be a valid installation. I followed the rest of the guide to the letter, including setting up the `zfs-mount-generator`. When I got to the point where I rebooted into the new installation for the first time (i.e. not using the live usb), I got dropped into an EFI options menu that would only let me get to the grub prompt from there. I couldn't figure out how to get the system to boot. I was so surprised by this, that I thought I had made a mistake, and I went through the entire installation process again with the same result.

Thinking about this, the only thing I can come up with is that somehow the `zfs-mount-generator` is not used on first boot, so things are mounting in the incorrect order and the system can't boot. Once I went back and used the exact dataset layout from the guide, things worked fine, so it wasn't some other problem with my installation I'm pretty sure. I've also (after the first boot) moved some datasets around to more closely replicate the above, and it boots fine. So, it seems to just be a first boot problem. My current dataset layout is below:
```
$ zfs list -o name,canmount,mountpoint,com.ubuntu.zsys:bootfs | grep pool
NAME                                                                                       CANMOUNT  MOUNTPOINT                    COM.UBUNTU.ZSYS:BOOTFS
bpool                                                                                       off  /boot                                               -
bpool/BOOT                                                                                  off  none                                                -
bpool/BOOT/ubuntu_v49l6x                                                                     on  /boot                                               -
rpool                                                                                       off  /                                                   -
rpool/ROOT                                                                                  off  none                                                -
rpool/ROOT/ubuntu_v49l6x                                                                     on  /                                                   yes
rpool/ROOT/ubuntu_v49l6x/usr                                                                off  /usr                                                no
rpool/ROOT/ubuntu_v49l6x/var                                                                off  /var                                                no
rpool/ROOT/ubuntu_v49l6x/var/lib                                                             on  /var/lib                                            no
rpool/ROOT/ubuntu_v49l6x/var/lib/AccountsService                                             on  /var/lib/AccountsService                            no
rpool/ROOT/ubuntu_v49l6x/var/lib/NetworkManager                                              on  /var/lib/NetworkManager                             no
rpool/ROOT/ubuntu_v49l6x/var/lib/apt                                                         on  /var/lib/apt                                        no
rpool/ROOT/ubuntu_v49l6x/var/lib/dpkg                                                        on  /var/lib/dpkg                                       no
rpool/ROOT/ubuntu_v49l6x/var/log                                                             on  /var/log                                            no
rpool/ROOT/ubuntu_v49l6x/var/spool                                                           on  /var/spool                                          no
rpool/USERDATA                                                                              off  /                                                   -
rpool/USERDATA/michael_20a1ei                                                                on  /home/michael                                       -
rpool/USERDATA/root_v49l6x                                                                   on  /root                                               -
rpool/srv                                                                                    on  /srv                                                no
rpool/usr                                                                                   off  /usr                                                -
rpool/usr/local                                                                              on  /usr/local                                          -
rpool/var                                                                                   off  /var                                                -
rpool/var/games                                                                              on  /var/games                                          -
rpool/var/lib                                                                               off  /var/lib                                            -
rpool/var/lib/docker                                                                         on  /var/lib/docker                                     -
rpool/var/mail                                                                               on  /var/mail                                           -
rpool/var/snap                                                                               on  /var/snap                                           -
rpool/var/www                                                                                on  /var/www                                            -

```

Am I correct on this? Is there any way to fix that so that so that you could successfully complete the first boot?

Failing some way to fix that, I think it would be great to have a warning in the installation instructions to keep people like me from shooting themselves in the foot.

**Comment by rlaager** [comment] 2020-07-13 05:09
If you are getting dropped to the GRUB prompt (i.e. not ever seeing the GRUB menu), then the problem is not the mount generator. That runs later, in userspace. You aren't even getting to the point of trying to boot a kernel,

Your `/boot` is listed as `canmount=noauto` in the broken case. That'd be my first guess as to what the problem is. So is the root filesystem (`rpool/ROOT/ubuntu_e2wti1`). You're also setting `canmount=on` for `rpool/ROOT/ubuntu_e2wti1/usr` and `rpool/ROOT/ubuntu_e2wti1/var`, which is almost certainly not what you want (whether that is the cause of this issue or not). If you're going for persistent, you definitely want `/srv` as `rpool/srv`, so your working example is correct in that regard and the broken example is wrong.

If you change all of those things, hopefully it will work.

The remaining differences are the ones you actually want. While both exist in both cases, the mounted `/var/lib` goes from being `rpool/ROOT/ubuntu_e2wti1/var/lib` to `rpool/var/lib`. `/var/log` and `/var/spool` move from `rpool/ROOT/ubuntu_e2wti1/var/...` to `rpool/var/...`.

**Comment by albertmichaelj** [comment] 2020-07-13 12:47
Thanks for responding! Ok, so it's probably not the mount generator.

However, I'm glad you brought up the `canmount=noauto` for both `bpool/BOOT/ubuntu_5235te` and `rpool/ROOT/ubuntu_5235te`. This is something I still am very confused by. To be clear, I followed the instructions to the letter for a single disk, no encryption, UEFI boot installation except for creating the datasets in Step 3 part 3. I was so surprised by the first failed installation that I was very , very careful in copy and pasting the second time. The `/` and `/boot` datasets are created in Step 3 part 2, so that was a copy and paste. I noticed it and I was really confused by it because I knew that eventually those were going to have to be set to mount. However, nowhere in the installation instructions do you switch those datasets back to `canmount=on`. In fact in Step 3 part 8, the installation instructions say to do this to refresh the cache:
```
zfs set canmount=noauto bpool/BOOT/ubuntu_$UUID
zfs set canmount=noauto rpool/ROOT/ubuntu_$UUID
```

I was so confused by this when I was doing the installation (even before things broke) that I did a `ctrl-f` and looked for every case of `canmount` in the installation instructions and those datasets are never set to `on`. That being said, when I followed the instructions fully (i.e. also create the same datasets as in Step 3 part 3), somehow the datasets are set to `canmount=on`. So, this must happen automagically somewhere, but I can't identify where. My custom dataset layout maybe kept that from happening, but for the life of me I can't figure out how or why.

As for `rpool/srv` vs `rpool/ROOT/ubuntu_5235te/srv`, I understand that is closer to the persistent dataset example, but that shouldn't break the installation, right? I'm sure that might have issues for rollbacks, but for the installation, I think that should be innocuous. I also can't imagine why setting `canmount=on` for `rpool/ROOT/ubuntu_5235te/var` and `rpool/ROOT/ubuntu_5235te/usr` would break the installation, but I again, I can't imagine why anything I did would break the installation.

Also, just FYI, the remaining differences are there because I couldn't move those datasets from a running system, and I didn't have the ability to boot off a live cd to move them.

**Comment by rlaager** [comment] 2020-07-14 21:49
You’re right. IIRC, the root and boot are supposed to be canmount=noauto as you can have more than one. So they are mounted by the initrd. I wasn’t thinking clearly before, I guess.

/srv shouldn’t matter. So yeah, I don’t get it either.

**Comment by albertmichaelj** [comment] 2020-07-14 22:07
My gut says that it has something to do with the `canmount=noauto` anyway. When I followed the installation instructions fully, after rebooting, I can clearly see that the datasets `bpool/BOOT/ubuntu_5235te` and `rpool/ROOT/ubuntu_5235te` now have `canmount=on` set, so in that first boot, maybe initrd is auto selecting the only possible "system" (in zsys terminology) and setting it to `canmount=on`? If so, then maybe something to do with the persistent datasets is getting in the way of this auto selection.

If I have time, though it may not be soon, I may try installing using my persistent data set layout in a VM and setting `canmount=on` on the `bpool/BOOT/ubuntu_5235te` and `rpool/ROOT/ubuntu_5235te` datasets before rebooting. My strong suspicion is that the reboot will be just fine. I suspect this because on future reboots those datasets will have `canmount=on` (however it gets set) and the system seems to operate fine with persistent datasets after the first reboot.

**Comment by rlaager** [comment] 2020-07-26 03:42
I'm going to close this. I won't have time to look at this particular configuration any time soon. If you get a chance to retest, I'd be interested to know what you find. If you get to the bottom of it, I can make changes to the HOWTO and/or help shuttle information/patches to upstream/Ubuntu.

**Closed by rlaager** 2020-07-26 03:42 UTC
Labels: documentation, question
