### ISSUE TITLE
NixOS: mention relevant settings instead of using dotfiles repo

### ISSUE THREAD

**Issue by SuperSandro2000** [openzfs/openzfs-docs#411] opened 2023-04-01 15:08 UTC
The NixOS guide right now guides people to clone a dotfiles repo (https://github.com/openzfs/openzfs-docs/blob/master/docs/Getting%20Started/NixOS/Root%20on%20ZFS/3-system-configuration.rst) and change some settings in there, instead of explaining what are the relevant settings people should set in their NixOS configuration.

Setting up ZFS on NixOS is pretty easy and IMO cloning some extra config should not be required, as I believe that the guide could fit on one screen in standard text size when leaving out the explanations.
There are a handful of module options (https://search.nixos.org/options?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=zfs) which people should be taught about and recommended to enable (autoScrub, autoTrim, etc)

**Comment by ne9z** [comment] 2023-04-01 15:45
> The NixOS guide right now guides people to clone a dotfiles repo
> (https://github.com/openzfs/openzfs-docs/blob/master/docs/Getting%20Started/NixOS/Root%20on%20ZFS/3-system-configuration.rst)
> and change some settings in there, instead of explaining what are the
> relevant settings people should set in their NixOS configuration.

So would you prefer the previous version of the guide instead? As in
this revision
https://github.com/openzfs/openzfs-docs/tree/9e6d2461c3f48df36ea324a2c9ecdda06707266e/docs/Getting%20Started/NixOS/Root%20on%20ZFS

Instead of hacking the output of nixos-generate-config, a flake repo is
used instead, because of reproducibility.  I do not think using a lot of
sed, tee and heredoc is superior to a dotfiles repo.

> Setting up ZFS on NixOS is pretty easy and IMO cloning some extra
> config should not be required, as I believe that the guide could fit
> on one screen in standard text size when leaving out the explanations.

My personal belief is that, it is not doable if our goal is to minimize
the size of the guide.

Or you can draft a new, shorter guide and we can discuss it here.

> There are a handful of module options
> (https://search.nixos.org/options?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=zfs)
> which people should be taught about and recommended to enable
> (autoScrub, autoTrim, etc)

Nope, that's the job of NixOS wiki.

The sole and only purpose of the guide is to let people install an Root
on ZFS system.  Anything else that does not involve repartitioning the
disks or changing the dataset layout is out of scope and should be
documented elsewhere.

This guide suffered from extreme feature creep before, and for the sake
of maintainability, we should not let that happen again.

**Comment by ne9z** [comment] 2023-04-01 16:07
Let me reiterate what would be lost if we do not use a flake repo for
system configuration:

The configuration will be no longer reproducible.

ARM64 support will be dropped.

Immutable root support will be dropped.

SSH remote encryption will be dropped.

Managing multiple hosts in single repo will be dropped.

Personally, I think the above features is not so worthless as to be
dropped without any further discussion.

We have another option.  The repo is currently controlled by a single
person, myself, which is not so ideal.  If there are enough interest, we
can create another template flake repo and benefit from community
oversight instead.

**Comment by mariaa144** [comment] 2023-04-03 14:40
I think the dot repo is a great idea but it does need a little work in my opinion. I love the features you mentioned! I did need to study the repo for myself to make sure it was changing any defaults which would surprise me.

It is a little bit of work to change the host from `exampleHost` to something else. It involves 3 changes I think. A change in`configuration.nix` a rename of the `exampleHost` directory and a change in the `default.nix` for the host. I'm not sure if it can get easier but documenting might be a good idea.

**Comment by ne9z** [comment] 2023-04-03 14:49
That would definitely be a good idea!

Right now I'm a bit busy offline, so that I can't do much documentation
for the repo.  Fortunately I have cleaned up the repo so that only
options strictly necessary for the guide is included.  Right now there
are about 500 lines of code in total, which would make documentation a
bit easier.

If you have time, you can fork my repo then make a pull request there.

**Comment by mariaa144** [comment] 2023-04-03 19:06
No matter if a repo is used, which I prefer, or if it is a single config, I would like the configuration for the guide to get to a stable point.

I have been setting up NixOS machines with the guide over several months and every machine is a little different. The machines use immutability, full disk encryption, initd ssh and initd tor access. I'm also interested in immutable home manager setup for users.

I'm happy to test the features I use and help maintain the configuration whether it be an advanced flake or single config. I guess it would make sense to have a basic config and an advanced config but I'm sure if doing that is maintainable.

I agree the features like autoScrub and autoTrim should be known to people setting up a ZFS system. I'm not sure if that is the job of the guide but it probably should be in the documentation or comments.

**Comment by ne9z** [comment] 2023-04-03 20:06
Maria ***@***.***> writes:

> No matter if a repo is used, which I prefer, or if it is a single
> config, I would like the configuration for the guide to get to a
> stable point.

I think the guide and the template flake repo is now stable.

> I have been setting up NixOS machines with the guide over several
> months and every machine is a little different. The machines use
> immutability, full disk encryption, initd ssh and initd tor
> access. I'm also interested in immutable home manager setup for users.

You can see an example of immutable home manager in the "personal" branch
of the template repo.

> I'm happy to test the features I use and help maintain the
> configuration whether it be an advanced flake or single config.
> I guess it would make sense to have a basic config and an advanced
> config but I'm sure if doing that is maintainable.

A "simple", non-flake config will be a maintainance nightmare.  I have
maintained that "simple" guide for a year and switched to flake in March
2023.

> I agree the features like autoScrub and autoTrim should be known to
> people setting up a ZFS system. I'm not sure if that is the job of the
> guide but it probably should be in the documentation or comments.

The guide should be easy to follow and be brief and concise.  Anything
that can be done post installation, should and will be done post
installation.

I have neither the time, the effort, nor the interest to document and
test every possible combination of configurations.

**Comment by SuperSandro2000** [comment] 2023-04-05 16:24
> So would you prefer the previous version of the guide instead? As in this revision

Yes, with some exceptions and details like I would replace the commands to programmatically edit the config files with diffs explaining people what they need to change. It gives them the ability to incorporate ZFS into their possible existing config and highlights the modularity of NixOS and is not suggesting that the zfs support requires an extra repo due to complexity and upstream deficiencies.

> Instead of hacking the output of nixos-generate-config, a flake repo is
used instead, because of reproducibility.  I do not think using a lot of
sed, tee and heredoc is superior to a dotfiles repo.

I don't think changing ``hardware-configuration.nix`` to some extend is wrong. The script generating it is only supposed to support 95% to 98% of the use cases and it is generally accepted to edit a few lines in it. I think user templating is avoided to keep complexity low.

> My personal belief is that, it is not doable if our goal is to minimize
the size of the guide.

I don't think it is a problem if the guide is slightly longer and also easier to understand what is happening. As long as the steps are easy to follow and avoid heavy copy pasting I am fine with it.

[I'll some more comments later hopefully keeping the discussion open and focused]

**Comment by ne9z** [comment] 2023-04-05 16:58
Sandro ***@***.***> writes:

>> So would you prefer the previous version of the guide instead? As in this revision
>
> Yes, with some exceptions and details like I would replace the
> commands to programmatically edit the config files with diffs
> explaining people what they need to change. It gives them the ability
> to incorporate ZFS into their possible existing config and highlights
> the modularity of NixOS and is not suggesting that the zfs support
> requires an extra repo due to complexity and upstream deficiencies.

You can write a draft based on that, and I will see to it and test it
out.

>> Instead of hacking the output of nixos-generate-config, a flake repo is
>> used instead, because of reproducibility.  I do not think using a lot
>> of sed, tee and heredoc is superior to a dotfiles repo.
>
> I don't think changing ``hardware-configuration.nix`` to some extend
> is wrong. The script generating it is only supposed to support 95% to
> 98% of the use cases and it is generally accepted to edit a few lines
> in it. I think user templating is avoided to keep complexity low.

How is the complexity lower with hardware-configuration.nix?  I fail to
understand.  You will be editing the template repo anyway so there is no
difference.

>> My personal belief is that, it is not doable if our goal is to
>> minimize the size of the guide.
>
> I don't think it is a problem if the guide is slightly longer and also
> easier to understand what is happening.

I have repeatedly stated that you are welcomed to add as much comment as
you want to my repo, to explain what is happening.

Nobody cares about those details during installation,  they just want
**get things done**.  Do you need in-depth explanation for ZFS
architecture during installation?

> As long as the steps are easy to follow and avoid heavy copy pasting I
> am fine with it.

You are combining black and white and will get neither black or white.

Easy to follow, and avoid heavy copy-pasting, then you are asking for an
one-liner installation script.

**Comment by ne9z** [comment] 2023-04-05 17:03
>> So would you prefer the previous version of the guide instead? As in this revision
>
> Yes, with some exceptions and details like I would replace the
> commands to programmatically edit the config files with diffs
> explaining people what they need to change. It gives them the ability
> to incorporate ZFS into their possible existing config and highlights
> the modularity of NixOS and is not suggesting that the zfs support
> requires an extra repo due to complexity and upstream deficiencies.

I strictly oppose the your opinion that

> incorporate ZFS into their possible existing config.

The purpose of this guide is to get NixOS installed, minimally.  That is
it. Not any more, not any less.

This guide is not about "incorporate ZFS into their possible existing
config".  If I was going to do that, someone will ask me to do the
troubleshooting that "why my config combined with yours does not boot",
let me refer you to

https://github.com/openzfs/openzfs-docs/issues/413

**Comment by ne9z** [comment] 2023-04-05 17:12
So, let me state explicitly my principles.

Write and simplify a guide as much as possible, and as fool-proof and as
reproducible as possible.  Make a self-contained guide so easy to
install and so easy to follow that it is guaranteed to boot and work
when the computer reboots.

No optional configuration. No advanced configuration.  No multi-choice
configuration.  The guide must be strictly linear.

As long as I am the maintainer of the guides, I will stick to my
principles, which are fundamentally incompatible with the changes you
are suggesting.

I deeply appreciate your discussion on this subject, but you should also
be aware of the principles that I am trying very hard to uphold.

**Comment by SuperSandro2000** [comment] 2023-04-16 19:26
> No optional configuration. No advanced configuration. No multi-choice configuration. The guide must be strictly linear.

Keeping variations low is good in making everything more linear and easier to support but zfs has some options that can't be fully ignored like you don't necessarily have enough disks for mirrored boot, want immutable root or you want zfs also on storage disks that are not part of the root disk.

> I strictly oppose the your opinion that

I believe that people than have a harder time learning the ideas behind what they are doing and just copy paste commands. Ideally a good guide should learn people how and why they are doing things, so that they can help themselves if things don't work correct.

> How is the complexity lower with hardware-configuration.nix?  I fail to
understand.  You will be editing the template repo anyway so there is no
difference.

If you want to install nixos you need to run ``nixos-generate-config`` anyway and then double checking that all disks and partitions show up and potentially fixing one or two entries should be doable.

> Nobody cares about those details during installation,  they just want
**get things done**.  Do you need in-depth explanation for ZFS
architecture during installation?

If people really just want to storage they don't want to maintain or know at least a little about, they should rather buy a SaaS solution somewhere.

**Comment by ne9z** [comment] 2023-04-17 06:51
Sandro ***@***.***> writes:


> Keeping variations low is good in making everything more linear and
> easier to support but zfs has some options that can't be fully ignored
> like you don't necessarily have enough disks for mirrored boot, want
> immutable root or you want zfs also on storage disks that are not part
> of the root disk.
>

Mirrored boot is covered in one single sentence during pool creation:

   If not using a multi-disk setup, remove mirror.

Nothing else is needed.  Mirrored bootloader is automatically handled in
the template config, which automatically detects if one or more disks
are used.

> Immutable root

Covered in one single sentence during introduction:

   Immutable root can be enabled or disabled by setting
   zfs-root.boot.immutable option inside per-host configuration.

I do not recommend enable this option to first-time users anyway, it
would erase data, only to make the user perplexed and angry.

> on storage disks that are not part of the root disk.

I do not like to repeat myself, but just to remind you:

  Anything that can be done post-installation, should and must be done
  post-installation, and documented elsewhere.

This is not related to the installation.  Without that disk, the system
will boot, and the related documentation is therefore out-of-scope.
Besides, NixOS wiki already has good docs for that, no need to duplicate
them here.

> I believe that people than have a harder time learning the ideas
> behind what they are doing and just copy paste commands. Ideally a
> good guide should learn people how and why they are doing things, so
> that they can help themselves if things don't work correct.
>

Sure.  You can add comments both to the guide and to the flake repo as
you see fit.  There can be both copy-pasting and detailed commentary.
There is nothing incompatible between the two.

The guide is quite terse now, as I am busy doing my math bachelor at TU
Berlin.  So any comments would be welcome and much appreciated.

Also, the guide in the works now uses literate programming to enable
CI/CD tests, so each and every change would be tested.

   https://github.com/openzfs/openzfs-docs/pull/424

> If you want to install nixos you need to run ``nixos-generate-config``
> anyway and then double checking that all disks and partitions show up
> and potentially fixing one or two entries should be doable.

That is not necessary with the guide, because we already have full
knowledge of the dataset and partition layout.  Every option is
carefully chosen and tested to be working in the upcoming CI/CD test to
ensure the template repo is working.

I will also mention that nixos-generate-config does not handle encrypted
config very well.  For example, on my machine it generates the following
config:


  swapDevices =
    [ { device = "/dev/disk/by-uuid/771b148e-c00e-4735-bf35-d5a24ce67daf"; }
    ];

When in reality it is randomly encrypted and should be configured like this:

     swapDevices =
     [{
       device = "/dev/disk/by-id//ata-TOSHIBA_Q300._46DB5111K1MU-part4";
       deviceName = "dev-disk-byx2did-atax2dTOSHIBA_Q300._46DB5111K1MUx2dpart4";
       discardPolicy = "both";
       randomEncryption = {
         allowDiscards = true;
         cipher = "aes-xts-plain64";
         enable = true;
         source = "/dev/urandom";
       };
       realDevice =
         "/dev/mapper/dev-disk-byx2did-atax2dTOSHIBA_Q300._46DB5111K1MUx2dpart4";
     }]


> If people really just want to storage they don't want to maintain or
> know at least a little about, they should rather buy a SaaS solution
> somewhere.

Not at all.  Many people still want to customize the window manager or
desktop environment to their daily workflow.  This is not covered by any
SaaS solution.

Here, the guide aims to provide a solid foundation to build their other
customizations upon.  But as for how to customize, look elsewhere, not
here.

**Closed** 2024-01-24 08:13 UTC
